# CMake generated Testfile for 
# Source directory: R:/workspaces/Special-Relativity-in-Financial-Modeling
# Build directory: R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[MomentumUnitTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_momentum.exe")
  set_tests_properties([=[MomentumUnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;129;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[MomentumUnitTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_momentum.exe")
  set_tests_properties([=[MomentumUnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;129;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[MomentumUnitTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_momentum.exe")
  set_tests_properties([=[MomentumUnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;129;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[MomentumUnitTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_momentum.exe")
  set_tests_properties([=[MomentumUnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;129;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[MomentumUnitTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[EdgeCaseBoundaryTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_edge_cases.exe")
  set_tests_properties([=[EdgeCaseBoundaryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;144;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[EdgeCaseBoundaryTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_edge_cases.exe")
  set_tests_properties([=[EdgeCaseBoundaryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;144;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[EdgeCaseBoundaryTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_edge_cases.exe")
  set_tests_properties([=[EdgeCaseBoundaryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;144;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[EdgeCaseBoundaryTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_edge_cases.exe")
  set_tests_properties([=[EdgeCaseBoundaryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;144;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[EdgeCaseBoundaryTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[LorentzInvariantTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_lorentz_invariants.exe")
  set_tests_properties([=[LorentzInvariantTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;157;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[LorentzInvariantTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_lorentz_invariants.exe")
  set_tests_properties([=[LorentzInvariantTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;157;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[LorentzInvariantTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_lorentz_invariants.exe")
  set_tests_properties([=[LorentzInvariantTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;157;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[LorentzInvariantTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_lorentz_invariants.exe")
  set_tests_properties([=[LorentzInvariantTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;157;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[LorentzInvariantTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[IntervalGapTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_interval_gaps.exe")
  set_tests_properties([=[IntervalGapTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;170;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[IntervalGapTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_interval_gaps.exe")
  set_tests_properties([=[IntervalGapTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;170;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[IntervalGapTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_interval_gaps.exe")
  set_tests_properties([=[IntervalGapTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;170;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[IntervalGapTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_interval_gaps.exe")
  set_tests_properties([=[IntervalGapTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;170;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[IntervalGapTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[LorentzTransformTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_lorentz_transform.exe")
  set_tests_properties([=[LorentzTransformTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;183;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[LorentzTransformTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_lorentz_transform.exe")
  set_tests_properties([=[LorentzTransformTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;183;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[LorentzTransformTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_lorentz_transform.exe")
  set_tests_properties([=[LorentzTransformTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;183;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[LorentzTransformTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_lorentz_transform.exe")
  set_tests_properties([=[LorentzTransformTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;183;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[LorentzTransformTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[BetaCalculatorLorentzTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_beta_calculator_lorentz.exe")
  set_tests_properties([=[BetaCalculatorLorentzTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;196;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[BetaCalculatorLorentzTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_beta_calculator_lorentz.exe")
  set_tests_properties([=[BetaCalculatorLorentzTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;196;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[BetaCalculatorLorentzTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_beta_calculator_lorentz.exe")
  set_tests_properties([=[BetaCalculatorLorentzTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;196;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[BetaCalculatorLorentzTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_beta_calculator_lorentz.exe")
  set_tests_properties([=[BetaCalculatorLorentzTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;196;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[BetaCalculatorLorentzTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[MarketManifoldTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_market_manifold.exe")
  set_tests_properties([=[MarketManifoldTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;208;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[MarketManifoldTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_market_manifold.exe")
  set_tests_properties([=[MarketManifoldTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;208;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[MarketManifoldTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_market_manifold.exe")
  set_tests_properties([=[MarketManifoldTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;208;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[MarketManifoldTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_market_manifold.exe")
  set_tests_properties([=[MarketManifoldTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;208;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[MarketManifoldTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[MetricTensorTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_metric_tensor.exe")
  set_tests_properties([=[MetricTensorTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;222;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[MetricTensorTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_metric_tensor.exe")
  set_tests_properties([=[MetricTensorTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;222;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[MetricTensorTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_metric_tensor.exe")
  set_tests_properties([=[MetricTensorTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;222;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[MetricTensorTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_metric_tensor.exe")
  set_tests_properties([=[MetricTensorTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;222;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[MetricTensorTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[GeodesicTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_geodesic.exe")
  set_tests_properties([=[GeodesicTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;234;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[GeodesicTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_geodesic.exe")
  set_tests_properties([=[GeodesicTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;234;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[GeodesicTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_geodesic.exe")
  set_tests_properties([=[GeodesicTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;234;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[GeodesicTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_geodesic.exe")
  set_tests_properties([=[GeodesicTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;234;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[GeodesicTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ChristoffelTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_christoffel.exe")
  set_tests_properties([=[ChristoffelTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;246;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ChristoffelTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_christoffel.exe")
  set_tests_properties([=[ChristoffelTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;246;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ChristoffelTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_christoffel.exe")
  set_tests_properties([=[ChristoffelTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;246;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ChristoffelTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_christoffel.exe")
  set_tests_properties([=[ChristoffelTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;246;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[ChristoffelTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[FullPipelineIntegrationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_full_pipeline.exe")
  set_tests_properties([=[FullPipelineIntegrationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;262;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[FullPipelineIntegrationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_full_pipeline.exe")
  set_tests_properties([=[FullPipelineIntegrationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;262;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[FullPipelineIntegrationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_full_pipeline.exe")
  set_tests_properties([=[FullPipelineIntegrationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;262;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[FullPipelineIntegrationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_full_pipeline.exe")
  set_tests_properties([=[FullPipelineIntegrationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;262;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[FullPipelineIntegrationTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[BacktesterTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_backtester.exe")
  set_tests_properties([=[BacktesterTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;279;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[BacktesterTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_backtester.exe")
  set_tests_properties([=[BacktesterTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;279;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[BacktesterTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_backtester.exe")
  set_tests_properties([=[BacktesterTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;279;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[BacktesterTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_backtester.exe")
  set_tests_properties([=[BacktesterTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;279;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[BacktesterTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[PerformanceMetricsTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_performance_metrics.exe")
  set_tests_properties([=[PerformanceMetricsTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;295;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[PerformanceMetricsTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_performance_metrics.exe")
  set_tests_properties([=[PerformanceMetricsTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;295;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[PerformanceMetricsTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_performance_metrics.exe")
  set_tests_properties([=[PerformanceMetricsTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;295;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[PerformanceMetricsTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_performance_metrics.exe")
  set_tests_properties([=[PerformanceMetricsTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;295;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[PerformanceMetricsTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SimdAccelerationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Debug/test_simd.exe")
  set_tests_properties([=[SimdAccelerationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;436;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SimdAccelerationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/Release/test_simd.exe")
  set_tests_properties([=[SimdAccelerationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;436;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SimdAccelerationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/MinSizeRel/test_simd.exe")
  set_tests_properties([=[SimdAccelerationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;436;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SimdAccelerationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_fresh2/RelWithDebInfo/test_simd.exe")
  set_tests_properties([=[SimdAccelerationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;436;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[SimdAccelerationTests]=] NOT_AVAILABLE)
endif()
subdirs("_deps/googletest-build")
subdirs("_deps/googlebenchmark-build")
