# CMake generated Testfile for 
# Source directory: R:/workspaces/Special-Relativity-in-Financial-Modeling
# Build directory: R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[MomentumUnitTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/Debug/test_momentum.exe")
  set_tests_properties([=[MomentumUnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;65;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[MomentumUnitTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/Release/test_momentum.exe")
  set_tests_properties([=[MomentumUnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;65;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[MomentumUnitTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/MinSizeRel/test_momentum.exe")
  set_tests_properties([=[MomentumUnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;65;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[MomentumUnitTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/RelWithDebInfo/test_momentum.exe")
  set_tests_properties([=[MomentumUnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;65;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[MomentumUnitTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[EdgeCaseBoundaryTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/Debug/test_edge_cases.exe")
  set_tests_properties([=[EdgeCaseBoundaryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;78;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[EdgeCaseBoundaryTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/Release/test_edge_cases.exe")
  set_tests_properties([=[EdgeCaseBoundaryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;78;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[EdgeCaseBoundaryTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/MinSizeRel/test_edge_cases.exe")
  set_tests_properties([=[EdgeCaseBoundaryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;78;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[EdgeCaseBoundaryTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/RelWithDebInfo/test_edge_cases.exe")
  set_tests_properties([=[EdgeCaseBoundaryTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;78;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[EdgeCaseBoundaryTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[IntervalGapTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/Debug/test_interval_gaps.exe")
  set_tests_properties([=[IntervalGapTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;89;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[IntervalGapTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/Release/test_interval_gaps.exe")
  set_tests_properties([=[IntervalGapTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;89;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[IntervalGapTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/MinSizeRel/test_interval_gaps.exe")
  set_tests_properties([=[IntervalGapTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;89;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[IntervalGapTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/RelWithDebInfo/test_interval_gaps.exe")
  set_tests_properties([=[IntervalGapTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;89;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[IntervalGapTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SimdAccelerationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/Debug/test_simd.exe")
  set_tests_properties([=[SimdAccelerationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;249;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SimdAccelerationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/Release/test_simd.exe")
  set_tests_properties([=[SimdAccelerationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;249;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SimdAccelerationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/MinSizeRel/test_simd.exe")
  set_tests_properties([=[SimdAccelerationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;249;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SimdAccelerationTests]=] "R:/workspaces/Special-Relativity-in-Financial-Modeling/build_test/RelWithDebInfo/test_simd.exe")
  set_tests_properties([=[SimdAccelerationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;249;add_test;R:/workspaces/Special-Relativity-in-Financial-Modeling/CMakeLists.txt;0;")
else()
  add_test([=[SimdAccelerationTests]=] NOT_AVAILABLE)
endif()
subdirs("_deps/googlebenchmark-build")
